export const OPEN_ADD_NEW_RESOURCE_DIALOG = 'OPEN_ADD_NEW_RESOURCE_DIALOG';
export const CLOSE_ADD_NEW_RESOURCE_DIALOG = 'CLOSE_ADD_NEW_RESOURCE_DIALOG';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';

export const FETCH_MENU_LIST_REQUEST = 'FETCH_MENU_LIST_REQUEST';
export const FETCH_MENU_LIST_FAILURE = 'FETCH_MENU_LIST_FAILURE';
export const FETCH_MENU_LIST_SUCCESS = 'FETCH_MENU_LIST_SUCCESS';

export const FETCH_MENU_RESOURCES_OPTIONS_REQUEST = 'FETCH_MENU_RESOURCES_OPTIONS_REQUEST';
export const FETCH_MENU_RESOURCES_OPTIONS_FAILURE = 'FETCH_MENU_RESOURCES_OPTIONS_FAILURE';
export const FETCH_MENU_RESOURCES_OPTIONS_SUCCESS = 'FETCH_MENU_RESOURCES_OPTIONS_SUCCESS';

export const FETCH_SERVER_STATUS_REQUEST = 'FETCH_SERVER_STATUS_REQUEST';
export const FETCH_SERVER_STATUS_FAILURE = 'FETCH_SERVER_STATUS_FAILURE';
export const FETCH_SERVER_STATUS_SUCCESS = 'FETCH_SERVER_STATUS_SUCCESS';

export const INSERT_RESOURCE_REQUEST = 'INSERT_RESOURCE_REQUEST';
export const INSERT_RESOURCE_FAILURE = 'INSERT_RESOURCE_FAILURE';
export const INSERT_RESOURCE_SUCCESS = 'INSERT_RESOURCE_SUCCESS';

export const DELETE_LOG_REQUEST = 'DELETE_LOG_REQUEST';
export const DELETE_LOG_FAILURE = 'DELETE_LOG_FAILURE';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';

export const DOWNLOAD_LOG_FILE_REQUEST = 'DOWNLOAD_LOG_FILE_REQUEST';
export const DOWNLOAD_LOG_FILE_FAILURE = 'DOWNLOAD_LOG_FILE_FAILURE';
export const DOWNLOAD_LOG_FILE_SUCCESS = 'DOWNLOAD_LOG_FILE_SUCCESS';

export const start_server_REQUEST = 'start_server_REQUEST';
export const start_server_FAILURE = 'start_server_FAILURE';
export const start_server_SUCCESS = 'start_server_SUCCESS';

export const stop_server_REQUEST = 'stop_server_REQUEST';
export const stop_server_FAILURE = 'stop_server_FAILURE';
export const stop_server_SUCCESS = 'stop_server_SUCCESS';

export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_MENU = 'OPEN_MENU';
export const CLICK_MENU = 'CLICK_MENU';

export const LOGIN = 'LOGIN';

export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
