export const OPEN_ADD_NEW_RESOURCE_DIALOG = 'OPEN_ADD_NEW_RESOURCE_DIALOG';
export const CLOSE_ADD_NEW_RESOURCE_DIALOG = 'CLOSE_ADD_NEW_RESOURCE_DIALOG';

export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';

export const FETCH_MENU_LIST_REQUEST = 'FETCH_MENU_LIST_REQUEST';
export const FETCH_MENU_LIST_FAILURE = 'FETCH_MENU_LIST_FAILURE';
export const FETCH_MENU_LIST_SUCCESS = 'FETCH_MENU_LIST_SUCCESS';

export const FETCH_MENU_RESOURCES_OPTIONS_REQUEST = 'FETCH_MENU_RESOURCES_OPTIONS_REQUEST';
export const FETCH_MENU_RESOURCES_OPTIONS_FAILURE = 'FETCH_MENU_RESOURCES_OPTIONS_FAILURE';
export const FETCH_MENU_RESOURCES_OPTIONS_SUCCESS = 'FETCH_MENU_RESOURCES_OPTIONS_SUCCESS';

export const FETCH_SERVER_STATUS_REQUEST = 'FETCH_SERVER_STATUS_REQUEST';
export const FETCH_SERVER_STATUS_FAILURE = 'FETCH_SERVER_STATUS_FAILURE';
export const FETCH_SERVER_STATUS_SUCCESS = 'FETCH_SERVER_STATUS_SUCCESS';

export const INSERT_RESOURCE_REQUEST = 'INSERT_RESOURCE_REQUEST';
export const INSERT_RESOURCE_FAILURE = 'INSERT_RESOURCE_FAILURE';
export const INSERT_RESOURCE_SUCCESS = 'INSERT_RESOURCE_SUCCESS';

export const DELETE_LOG_REQUEST = 'DELETE_LOG_REQUEST';
export const DELETE_LOG_FAILURE = 'DELETE_LOG_FAILURE';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';

export const DOWNLOAD_LOG_FILE_REQUEST = 'DOWNLOAD_LOG_FILE_REQUEST';
export const DOWNLOAD_LOG_FILE_FAILURE = 'DOWNLOAD_LOG_FILE_FAILURE';
export const DOWNLOAD_LOG_FILE_SUCCESS = 'DOWNLOAD_LOG_FILE_SUCCESS';

export const start_server_REQUEST = 'start_server_REQUEST';
export const start_server_FAILURE = 'start_server_FAILURE';
export const start_server_SUCCESS = 'start_server_SUCCESS';

export const stop_server_REQUEST = 'stop_server_REQUEST';
export const stop_server_FAILURE = 'stop_server_FAILURE';
export const stop_server_SUCCESS = 'stop_server_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';

export const EMAIL_VERIFICATION_REQUEST = 'EMAIL_VERIFICATION_REQUEST';
export const EMAIL_VERIFICATION_REQUEST_FAILURE = 'EMAIL_VERIFICATION_REQUEST_FAILURE';
export const EMAIL_VERIFICATION_REQUEST_SUCCESS = 'EMAIL_VERIFICATION_REQUEST_SUCCESS';

export const SEND_PROFILE_INFO_REQUEST = 'SEND_PROFILE_INFO_REQUEST';
export const SEND_PROFILE_INFO_REQUEST_FAILURE = 'SEND_PROFILE_INFO_REQUEST_FAILURE';
export const SEND_PROFILE_INFO_REQUEST_SUCCESS = 'SEND_PROFILE_INFO_REQUEST_SUCCESS';

export const FETCH_PROFILE_INFO_REQUEST = 'FETCH_PROFILE_INFO_REQUEST';
export const FETCH_PROFILE_INFO_REQUEST_FAILURE = 'FETCH_PROFILE_INFO_REQUEST_FAILURE';
export const FETCH_PROFILE_INFO_REQUEST_SUCCESS = 'FETCH_PROFILE_INFO_REQUEST_SUCCESS';

export const FETCH_PROFILE_AVATAR_REQUEST = 'FETCH_PROFILE_AVATAR_REQUEST';
export const FETCH_PROFILE_AVATAR_REQUEST_FAILURE = 'FETCH_PROFILE_AVATAR_REQUEST_FAILURE';
export const FETCH_PROFILE_AVATAR_REQUEST_SUCCESS = 'FETCH_PROFILE_AVATAR_REQUEST_SUCCESS';

export const FETCH_BLOG_POSTS_REQUEST = 'FETCH_BLOG_POSTS_REQUEST';
export const FETCH_BLOG_POSTS_REQUEST_FAILURE = 'FETCH_BLOG_POSTS_REQUEST_FAILURE';
export const FETCH_BLOG_POSTS_REQUEST_SUCCESS = 'FETCH_BLOG_POSTS_REQUEST_SUCCESS';

export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_REQUEST_FAILURE = 'FETCH_VIDEOS_REQUEST_FAILURE';
export const FETCH_VIDEOS_REQUEST_SUCCESS = 'FETCH_VIDEOS_REQUEST_SUCCESS';

export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_MENU = 'OPEN_MENU';
export const CLICK_MENU = 'CLICK_MENU';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_EMAIL = 'SET_EMAIL';

export const CLEAR_LOGIN_REQUEST_RESULT = 'CLEAR_LOGIN_REQUEST_RESULT';
export const REMOVE_PROFILE_INFO = 'REMOVE_PROFILE_INFO';

export const FETCH_ENGLISH_CLASSES_REQUEST = 'FETCH_ENGLISH_CLASSES_REQUEST';
export const FETCH_ENGLISH_CLASSES_REQUEST_FAILURE = 'FETCH_ENGLISH_CLASSES_REQUEST_FAILURE';
export const FETCH_ENGLISH_CLASSES_REQUEST_SUCCESS = 'FETCH_ENGLISH_CLASSES_REQUEST_SUCCESS';

export const CREATE_ENGLISH_CLASS_REQUEST = 'CREATE_ENGLISH_CLASS_REQUEST';
export const CREATE_ENGLISH_CLASS_REQUEST_FAILURE = 'CREATE_ENGLISH_CLASS_REQUEST_FAILURE';
export const CREATE_ENGLISH_CLASS_REQUEST_SUCCESS = 'CREATE_ENGLISH_CLASS_REQUEST_SUCCESS';

export const FETCH_ENGLISH_CLASS_BY_ID_REQUEST = 'FETCH_ENGLISH_CLASS_BY_ID_REQUEST';
export const FETCH_ENGLISH_CLASS_BY_ID_REQUEST_FAILURE = 'FETCH_ENGLISH_CLASS_BY_ID_REQUEST_FAILURE';
export const FETCH_ENGLISH_CLASS_BY_ID_REQUEST_SUCCESS = 'FETCH_ENGLISH_CLASS_BY_ID_REQUEST_SUCCESS';

export const UPDATE_ENGLISH_CLASS_REQUEST = 'UPDATE_ENGLISH_CLASS_REQUEST';
export const UPDATE_ENGLISH_CLASS_REQUEST_FAILURE = 'UPDATE_ENGLISH_CLASS_REQUEST_FAILURE';
export const UPDATE_ENGLISH_CLASS_REQUEST_SUCCESS = 'UPDATE_ENGLISH_CLASS_REQUEST_SUCCESS';

export const DELETE_ENGLISH_CLASS_REQUEST = 'DELETE_ENGLISH_CLASS_REQUEST';
export const DELETE_ENGLISH_CLASS_REQUEST_FAILURE = 'DELETE_ENGLISH_CLASS_REQUEST_FAILURE';
export const DELETE_ENGLISH_CLASS_REQUEST_SUCCESS = 'DELETE_ENGLISH_CLASS_REQUEST_SUCCESS';

export const SUBSCRIBE_ENGLISH_CLASS_REQUEST = 'SUBSCRIBE_ENGLISH_CLASS_REQUEST';
export const SUBSCRIBE_ENGLISH_CLASS_REQUEST_FAILURE = 'SUBSCRIBE_ENGLISH_CLASS_REQUEST_FAILURE';
export const SUBSCRIBE_ENGLISH_CLASS_REQUEST_SUCCESS = 'SUBSCRIBE_ENGLISH_CLASS_REQUEST_SUCCESS';

export const FETCH_SUBSCRIPTIONS_REQUEST = 'FETCH_SUBSCRIPTIONS_REQUEST';
export const FETCH_SUBSCRIPTIONS_REQUEST_FAILURE = 'FETCH_SUBSCRIPTIONS_REQUEST_FAILURE';
export const FETCH_SUBSCRIPTIONS_REQUEST_SUCCESS = 'FETCH_SUBSCRIPTIONS_REQUEST_SUCCESS';

export const CLEAR_SELECTED_ENGLISH_CLASS = 'CLEAR_SELECTED_ENGLISH_CLASS';
