version: '3.7'

services:
  api:
    build: ./hello_world_backend
    command: gunicorn hello_world_backend.wsgi:application --bind 0.0.0.0:1234
    expose:
      - 1234
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/hello_world_backend/api/staticfiles
      - photos_volume:/home/hello_world_backend/api/photos

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  web:
    build: ./hello_world_frontend
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=www.hi-english.ir"
      - "VIRTUAL_PORT=80"

  api_nginx_server:
    build: ./api_nginx_server
    expose:
      - 8081
    depends_on:
      - api
    volumes:
      - static_volume:/home/hello_world_backend/api/staticfiles
    environment:
      - "VIRTUAL_HOST=api.hi-english.ir"
      - "VIRTUAL_PORT=8081"

  nginx_proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

volumes:
  postgres_data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/hello_world_service_db
  
  photos_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/hello_world_backend_photos
      
  static_volume:
      
    