version: '3.7'

services:
  api:
    build: ./hello_world_backend
    command: gunicorn hello_world_backend.wsgi:application --bind 0.0.0.0:1234
    # --certfile=/home/hello_world_backend/certs/api.halloenglish.com.crt --keyfile=/home/hello_world_backend/certs/api.halloenglish.com.key
    expose:
      - 1234
      - 443
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/hello_world_backend/api/staticfiles
      - photos_volume:/home/hello_world_backend/api/photos
      - ssl_cert_volume:/home/hello_world_backend/certs
    environment:
      - "VIRTUAL_HOST=api.hi-english.ir,api.halloenglish.com"
      - "VIRTUAL_PORT=1234"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  web:
    build: ./hello_world_frontend
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=www.hi-english.ir,www.halloenglish.com"
      - "VIRTUAL_PORT=80"

  # api_nginx_server:
  #   build: ./api_nginx_server
  #   expose:
  #     - 8081
  #   depends_on:
  #     - api
  #   volumes:
  #     - static_volume:/home/hello_world_backend/api/staticfiles

  #   environment:
  #     - "VIRTUAL_HOST=api.hi-english.ir,api.halloenglish.com"
  #     - "VIRTUAL_PORT=8081"

  nginx_proxy:
    build: ./api_nginx_server
    # image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ssl_cert_volume:/etc/nginx/certs
      - static_volume:/home/hello_world_backend/api/staticfiles

volumes:
  postgres_data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/hello_world_service_db
  
  photos_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/hello_world_backend_photos
  
  ssl_cert_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/halloenglish.com.ssl.certificate

  static_volume:
