version: '3.7'

services:
  api:
    build: ./hello_world_backend
    command: gunicorn hello_world_backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 1234
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  web:
    build: ./hello_world_frontend
    ports:
      - '80:80'

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/hello_world_service_db
      
    