version: '3.7'

services:
  api:
    build: ./hello_world_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hello_world_backend/:/usr/src/hello_world_backend/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  web:
    build: ./hello_world_frontend
    ports:
      - '80:80'

volumes:
  postgres_data: 
    external:
        name: /root/hello_world_service_db
      
    