version: '3.7'

services:
  api:
    build:
      context: ./hello_world_backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hello_world_backend/:/usr/src/hello_world_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
        
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  
volumes:
    postgres_data:
        driver: local
        driver_opts:
          o: bind
          type: none
          device: /home/arjmandi/hello_world_service_db