# Generated by Django 3.1 on 2020-12-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField()),
                ('skype_link', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='photos')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stream_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='learner', max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('skype_link', models.TextField()),
                ('is_completed', models.BooleanField()),
                ('avatar', models.ImageField(upload_to='photos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True)),
                ('english_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.englishclass')),
                ('profile_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profileinfo')),
            ],
        ),
        migrations.AddField(
            model_name='englishclass',
            name='members',
            field=models.ManyToManyField(through='api.Membership', to='api.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='englishclass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnglishClass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('snippet', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
