# Generated by Django 3.1 on 2020-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='user_type',
            field=models.CharField(default='learner', max_length=100),
        ),
    ]
