# Generated by Django 3.1 on 2020-12-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201207_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='profile_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Membership', to='api.profileinfo'),
        ),
    ]
