# Generated by Django 3.1 on 2020-10-02 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profileinfo_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='avatar',
        ),
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='photos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
