# Generated by Django 3.1 on 2020-10-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201002_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileavatar',
            old_name='owner',
            new_name='profile_info',
        ),
    ]
