# Generated by Django 3.1 on 2020-10-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201002_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatar',
            name='profile_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='api.profileinfo'),
        ),
    ]
